kaiyuanshe/osschat

- src/handlers/on-message.ts
When anyone say  "oss", bot will invite the person to the group "OSS Bot ChatOps" and reply a welcome message in the group.
Todo:
> add room join demo #12

- README.md
Add how to run the project and the success log.
> add how to run

- src/start-web.ts
```
[ ] Bug Fix
[x] Feature
```
```
[ ] Yes
[x] No
```
> show room id

- package.json
- src/chatops.ts
```
[ ] Bug Fix
[x] Feature
```
Related to #11 
```
[ ] Yes
[x] No
```
> Enable Urllink

- package.json
- src/handlers/on-message.ts
- src/managers/vote-manager.ts
```
[ ] Bug Fix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat:add vote manager to manage group with vote rules

- src/config.ts
> Add Quicksql Wechat group config

- src/config.ts
update dsextension to DSExtension to match getRepoRoom(issue-handlers.ts) method
> update dsextension to DSExtension

- src/config.ts
add oss chat for dolphinscheduler
> add oss chat for dolphinscheduler

- docs/how_to_use.md
> update spell error

- README.md
> add How to use link on Readme

- src/config.ts
add user group for dolphinscheduler
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add user group for dolphinscheduler

- src/issue-handlers.ts
> hide bot key

- src/issue-handlers.ts
```
[ ] Bug Fix
[ x ] Feature
```
This PR is for moving the repo name to the end of the title of the message for comments.
For more info, see issue #83  and PR #92 .
> move repo name to the end of the message title for comments

- .gitignore
- CHANGELOG.md
- README.md
- package.json
- scripts/sort-contributiveness.ts
> Add Changelog Generator Script

- docs/README.md
link issue is: #65 
Signed-off-by: 庄表伟 <zhuangbiaowei@gmail.com>
```
[ ] Bug Fix
[ ] Feature
[x] Other (Refactoring, Added tests, Documentation, ...)
```
Added some instructions on how to contribute.
```
[ ] Yes
[x] No
```
> docs: add How to contribute.

- README.md
```
[ ] Bug Fix
[ ] Feature
[x] Other (Refactoring, Added tests, Documentation, ...)
```
```
[ ] Yes
[x] No
```
> docs:  add document link to README.md

- package.json
```
[x] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Upgrade wechaty

- src/config.ts
add groups for DolphinScheduler
> add groups for DolphinScheduler

- src/config.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> added Tencent/wepy

- src/config.ts
add new chatroom for DolphinScheduler
> [Other] add new chatroom for DolphinScheduler

- package.json
- src/managers/vote-manager.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Bump wechaty

- src/config.ts
```
[ ] Bug Fix
[ ] Feature
[x] Other (Refactoring, Added tests, Documentation, ...)
```
Add another Wechat group "Doris开发者"
```
[ ] Yes
[x] No
```
> Add another wechat group of Doris

- src/config.ts
hi , I want to add new user group notification fro DolphinScheduler
> add user group 8 for Apache DolphinScheduler

- src/config.ts
Update dss and linkis wechat group
> Update dss and linkis wechat group

- src/config.ts
Add X-lab/open-digger wechat group 37
> Add X-lab/open-digger wechat group in config.ts

- bin/main.ts
- package.json
- src/issue-handlers.ts
- src/routers.ts
See: https://github.com/probot/probot/releases/tag/v11.0.0
> Upgrade Probot to v11

- docs/pages/how-to-use.md
> fix group id addr

- src/config-projects/apache.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add apache shenyu (incubating)

- src/config-projects/apache.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> @tuohai666 change shenyu to apache repo

- src/config-projects/others.ts
Add OS-EDU/KO--CSP Wechat group
> Add OS-EDU/KO--CSP wechat group in config.ts

- src/config-projects/webank.ts
```
```
-  Added linkis developer group
Added linkis developer group
```
[ ] No
```
> Added linkis developer group

- src/config-projects/streamnative.ts
```
[x] Feature
```
```
[x] No
```
> Add new configure file for KoP-SIG Chatroom

- src/config-projects/apache.ts
```
[ ] Bug Fix
[ ] Feature
[x] Other (Refactoring, Added tests, Documentation, ...)
```
Modify the chatroom of Doris
```
[ ] Yes
[x] No
```
> Modify the chatroom of Apache Doris

- src/config-projects/apache.ts
```
[x] Feature
```
- Add Apache Pegasus char room ID
```
[ ] Yes
[x] No
```
> Add Apache Pegasus char room ID

- src/config-projects/mod.ts
```
[x] Feature
```
```
[x] No
```
> Add streamnative to mod.ts

- src/config-projects/webank.ts
Modify the project name to apache/incubator-linkis
```
Other (Refactoring, Added tests, Documentation, ...)
```
- update webank.ts
```
No
```
> Modify the project name to apache/incubator-linkis

- src/config-projects/webank.ts
Modify the linkis project name to apache/incubator-linkis
```
```
- update webank.ts
Modify the linkis project name to apache/incubator-linkis
```
[ ] No
```
> Modify the linkis project name to apache/incubator-linkis

- src/config-projects/mod.ts
- src/config-projects/small-wu-pond.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add config file small-wu-pond

- src/config-projects/mod.ts
- src/config-projects/small-wu-pond.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> small-wu-pond.ts eslint --fix

- src/config-projects/apache.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add new group for Apache ShenYu community

- src/config-projects/openingo.ts
```
[ ] Bug Fix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add openingo config.
